---
- name: "Install Wordpress"
  hosts: client1
  gather_facts: yes
  become: yes
  vars:
    system_user: ansible
  pre_tasks:
    - name: Add the user 'www-data' with a primary group of 'www-data'
      user:
        name: www-data
        # group: www-data
        state: present
  roles:
    - role: 'roles'